# birch-cw — headless server, generated by add-host --server.
# Install with:  bootstrap-host birch-cw root@<ip>
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

{
  imports = [
    ./hardware-configuration.nix
    ../server-common.nix
    ../disko/single-disk-ext4.nix
  ];

  networking.hostName = "birch-cw";

  boot.kernelModules = [
    "kvm-amd"
    "vhost_vsock"
    "vhost"
  ];
  boot.extraModprobeConfig = ''
    options kvm_amd nested=1
  '';

  users.users.zspar.extraGroups = [ "kvm" ];

  # Standalone containerd for `ctr run --runtime io.containerd.kata.v2`.
  # Kata binaries themselves come from `kata-install` in the kata-containers
  # devshell (GitHub static release under /opt/kata). Those are generic
  # Linux ELFs, so nix-ld must replace NixOS's stub dynamic linker.
  virtualisation.containerd.enable = true;
  # `path` adds <entry>/bin to the unit PATH (see systemd.services.<name>.path).
  systemd.services.containerd.path = [ "/opt/kata" ];
  virtualisation.containerd.settings = {
    plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata = {
      runtime_type = "io.containerd.kata.v2";
    };
  };

  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = with pkgs; [
    glib
    pixman
    libseccomp
    numactl
    libcap
    libcap_ng
    libaio
    dtc
    libslirp
    liburing
    keyutils
    snappy
    lzo
    libpng
    libjpeg
    ncurses
    gnutls
    nettle
    gmp
    libtasn1
    libusb1
    spice
    usbredir
    virglrenderer
    mesa
    libdrm
    libepoxy
    libglvnd
    alsa-lib
    pulseaudio
    SDL2
  ];

  # sessionVariables from nix-ld do not apply to systemd units.
  systemd.services.containerd.environment = {
    NIX_LD = "/run/current-system/sw/share/nix-ld/lib/ld.so";
    NIX_LD_LIBRARY_PATH = lib.concatStringsSep ":" [
      "/run/current-system/sw/share/nix-ld/lib"
      "/opt/kata/lib"
      "/opt/kata/lib64"
    ];
  };

  # Target disk for disko (set via add-host --disk; wipes this disk on install).
  disko.devices.disk.main.device = "/dev/sdb";

  # Host-specific settings go here (services, extra packages, …).

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?
}
