# birch-cw — headless server, generated by add-host --server.
# Install with:  bootstrap-host birch-cw root@<ip>
{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../server-common.nix
    ../disko/single-disk-ext4.nix
  ];

  networking.hostName = "birch-cw";

  boot.kernelModules = [ "kvm-amd" ];

  users.users.zspar.extraGroups = [ "kvm" ];

  # Target disk for disko (set via add-host --disk; wipes this disk on install).
  disko.devices.disk.main.device = "/dev/sdb";

  # Host-specific settings go here (services, extra packages, …).

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?
}
