# HOSTNAME — generated by add-host; customize as needed.
{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../common.nix
    # DISPLAYLINK_IMPORT
  ];

  networking.hostName = "HOSTNAME";

  # Host-specific settings go here (LUKS, GPU, extra packages, ssh keys, …).

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.11"; # Did you read the comment?
}
